/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tcp.client;

import java.awt.event.WindowAdapter;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author luongtx
 */
public class ClientRoomFrm extends javax.swing.JFrame {

    /**
     * Creates new form RoomFrm
     */
    Client client;
    ArrayList<User> userList;
    public ClientRoomFrm(Client client) {
//        client.listenBattleRequest();
        initComponents();
        this.client = client;
        lbUser.setText(client.getCurrentUser().getUsername());
        updateRoom();
        this.addWindowListener(new WindowsClosedListener());
    }
    private class WindowsClosedListener extends WindowAdapter{
        @Override
        public void windowClosing(java.awt.event.WindowEvent windowEvent) {
            client.logout();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lstRoom = new java.awt.List();
        btnRefresh = new javax.swing.JButton();
        btnCombat = new javax.swing.JButton();
        btnViewRoom = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbUser = new javax.swing.JLabel();
        lbOnline = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRefresh.setBackground(new java.awt.Color(0, 255, 255));
        btnRefresh.setText("Refesh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnCombat.setBackground(new java.awt.Color(0, 255, 255));
        btnCombat.setText("Combat");
        btnCombat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCombatActionPerformed(evt);
            }
        });

        btnViewRoom.setBackground(new java.awt.Color(0, 255, 255));
        btnViewRoom.setText("View Room");

        btnLogout.setBackground(new java.awt.Color(153, 153, 153));
        btnLogout.setText("Log out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jLabel1.setText("Online users:");

        lbUser.setText("jLabel3");

        lbOnline.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(90, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbOnline)
                        .addGap(56, 56, 56)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lstRoom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbUser)
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCombat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLogout)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(lbOnline)))
                .addGap(19, 19, 19)
                .addComponent(lstRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(btnRefresh)
                .addGap(18, 18, 18)
                .addComponent(btnCombat)
                .addGap(18, 18, 18)
                .addComponent(btnViewRoom)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void updateRoom(){
        userList = client.getOnlineUsers();
        lstRoom.removeAll();
        userList.forEach((u) -> {
            ClientRoomFrm.lstRoom.add(u.getUsername());
        });
        lbOnline.setText(Integer.toString(userList.size()));
    }
    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        updateRoom();
    }//GEN-LAST:event_btnRefreshActionPerformed
    public int showConfirmDialog(Object msg, String title){
        return JOptionPane.showConfirmDialog(rootPane, msg, title, JOptionPane.OK_CANCEL_OPTION);
    }
    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        client.logout();
        new ClientLoginFrm(client).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnCombatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCombatActionPerformed
        // TODO add your handling code here:\
        String opponent = lstRoom.getSelectedItem();
        if(opponent==null) {
            JOptionPane.showMessageDialog(rootPane, "select an opponent!");
            return;
        }
        client.requestBattle(opponent);
    }//GEN-LAST:event_btnCombatActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCombat;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnViewRoom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbOnline;
    private javax.swing.JLabel lbUser;
    public static java.awt.List lstRoom;
    // End of variables declaration//GEN-END:variables
}
