/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tcp.test.client;

import java.awt.event.ActionListener;

/**
 *
 * @author luongtx
 */
public class RoomFrm extends javax.swing.JFrame {

    /**
     * Creates new form RoomFrm
     */
    public RoomFrm() {
        initComponents();
    }
    public void addRefreshListener(ActionListener refresh){
        btnRefresh.addActionListener(refresh);
    }
    public void addJoinRoomListener(ActionListener joinRoom){
        btnJoinRoom.addActionListener(joinRoom);
    }
    public void addViewRoomListener(ActionListener viewRoom){
        btnViewRoom.addActionListener(viewRoom);
    }
    public void addExitListener(ActionListener exit){
        btnExit.addActionListener(exit);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lstRoom = new java.awt.List();
        btnRefresh = new javax.swing.JButton();
        btnJoinRoom = new javax.swing.JButton();
        btnViewRoom = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRefresh.setBackground(new java.awt.Color(0, 255, 255));
        btnRefresh.setText("Refesh");

        btnJoinRoom.setBackground(new java.awt.Color(0, 255, 255));
        btnJoinRoom.setText("Join Room");

        btnViewRoom.setBackground(new java.awt.Color(0, 255, 255));
        btnViewRoom.setText("View Room");

        btnExit.setBackground(new java.awt.Color(0, 255, 255));
        btnExit.setText("Exit");

        jLabel1.setText("Online users:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lstRoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnViewRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(btnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnJoinRoom, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 114, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lstRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(btnRefresh)
                .addGap(18, 18, 18)
                .addComponent(btnJoinRoom)
                .addGap(18, 18, 18)
                .addComponent(btnViewRoom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(btnExit)
                .addGap(17, 17, 17))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnJoinRoom;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnViewRoom;
    private javax.swing.JLabel jLabel1;
    public static java.awt.List lstRoom;
    // End of variables declaration//GEN-END:variables
}
